#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    show-sql: true

spring:
  datasource:
    #driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blockbuster
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      #generate-ddl: false
      #show-sql: true
      # naming:
      #  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl